### ISSUE TITLE
Random Crash & Watchdog dont restart Add-on

### ISSUE THREAD

**Issue by ekkesa** [giuseppecastaldo/ha-addons#7]
The addon randomly dies, I have attached the log below. The watchdog service also does not restart it, once it dies.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[12:51:17] INFO: Installed custom component.
[2022-12-01T12:51:19.303] [INFO] default - Whatsapp Addon started.
[2022-12-01T12:51:20.655] [INFO] default - default client is ready.
/whatsapp.js:126
            const messageType = Object.keys(msg.message)[0]
                                       ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at EventEmitter.<anonymous> (/whatsapp.js:126:40)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.<anonymous> (/node_modules/@giuseppecastaldo/baileys/lib/Utils/event-buffer.js:47:16)
    at EventEmitter.emit (node:events:513:28)
    at Object.flush (/node_modules/@giuseppecastaldo/baileys/lib/Utils/event-buffer.js:88:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebSocket.<anonymous> (/node_modules/@giuseppecastaldo/baileys/lib/Socket/messages-recv.js:558:9)
Node.js v18.9.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by ekkesa** [comment]
I receive this message at start up - Even after a rebuild. Any suggestions will be appreciated.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[02:41:41] INFO: Installed custom component.
[2022-12-07T02:41:43.924] [INFO] default - Whatsapp Addon started.
[2022-12-07T02:41:45.841] [INFO] default - default client is ready.
/whatsapp.js:126
            const messageType = Object.keys(msg.message)[0]
                                       ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at EventEmitter.<anonymous> (/whatsapp.js:126:40)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.<anonymous> (/node_modules/@giuseppecastaldo/baileys/lib/Utils/event-buffer.js:47:16)
    at EventEmitter.emit (node:events:513:28)
    at Object.flush (/node_modules/@giuseppecastaldo/baileys/lib/Utils/event-buffer.js:88:16)
    at async WebSocket.<anonymous> (/node_modules/@giuseppecastaldo/baileys/lib/Socket/messages-recv.js:558:9)
Node.js v18.9.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by ekkesa** [comment]
Still experiencing this problem - I have not been able to pinpoint what is causing this. I suspect it might be something with "Community Group" messages, but cannot confirm.

**Comment by ekkesa** [comment]
Still experiencing this, it seems that "Security Code changed" messages also crashes the add-on. Currently I restart the add-on every hour, which is not ideal.

**Comment by giuseppecastaldo** [comment]
I'm working on it, please be patient.

**Comment by ekkesa** [comment]
Thank you! I really appreciate it... I'm try to provide as much as possible information for you to troubleshoot :-)

**Comment by ekkesa** [comment]
Thank you!

**Comment by ekkesa** [comment]
Hi, Unfortunately it seems to be more unstable now on 1.2.3 after the update. It seems to stop and the log is empty, so unfortunately I can't even supply information on why it crashed.

I will scratch around in the docker container to see if I can find some log traces.
