### ISSUE TITLE
[Bug]: This action requires the clientId field. Enter a valid value for clientId

### ISSUE THREAD

**Issue by Gaio-Christiano** [giuseppecastaldo/ha-addons#94]
### The problem

I installed yesterday on Home Assistant version 2024.10.1, Supervisor version 2024.10.0, Operating System 13.1.
The WhatsApp version is 1.4.1 and I can't send a single message and every time I try to send it, I get the error "This action requires the clientId field. Enter a valid value for clientId" and I don't know how to solve it.
I created another client and scanned the QR code and the same problem.
![wa 09](https://github.com/user-attachments/assets/93530844-8a50-4239-9ced-2be4d301a582)
![wa 08](https://github.com/user-attachments/assets/5f5cb991-82bd-46e9-9699-cd2ab35a60b3)
![wa 06](https://github.com/user-attachments/assets/3f591fcf-169b-4493-b2e0-72c09ea54062)
![wa 07](https://github.com/user-attachments/assets/466d0865-dc4d-4444-82eb-648b0bfbbf7d)
![wa 05](https://github.com/user-attachments/assets/3ae91889-7536-49d0-9b09-54df173c2b83)
![wa 04](https://github.com/user-attachments/assets/7d07050a-bf05-4a5f-b3d6-d424ee32396f)
![wa 03](https://github.com/user-attachments/assets/7523ae70-018f-4afe-9597-d0464aabb964)
![wa 02](https://github.com/user-attachments/assets/3e17505b-6721-4ff5-8765-5c0473c1d9d1)
![wa 01](https://github.com/user-attachments/assets/c45933e3-9138-43d7-82b0-1db7da97551e)

### What version of Home Assistant Core has the issue?

2024.10.1

### What version of the addon has the issue?

1.4.1

### What type of installation are you running?

Home Assistant OS

### Log information

```txt
2024-10-09 09:47:37.087 INFO (SyncWorker_5) [supervisor.docker.manager] Stopping addon_f4fdf59d_whatsapp_addon application
2024-10-09 09:47:44.334 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_f4fdf59d_whatsapp_addon application
2024-10-09 09:47:47.896 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on f4fdf59d/aarch64-addon-whatsapp_addon with version 1.4.1


s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[15:23:55] INFO: Installed custom component.
[2024-10-08T15:23:59.108] [INFO] default - Whatsapp Addon started.
[2024-10-08T15:24:03.608] [INFO] default - default client is ready.
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[18:46:19] INFO: Installed custom component.
[2024-10-08T18:46:47.184] [INFO] default - Whatsapp Addon started.
[2024-10-08T18:46:49.988] [INFO] default - default client is ready.
/whatsapp.js:240
      throw new WhatsappError(err.output.payload.statusCode);
            ^

WhatsappError: Send message failed. Whatsapp error 428: Connection Closed
    at WhatsappClient.sendPresenceUpdate (/whatsapp.js:240:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processTimers (node:internal/timers:504:9) {
  code: 428
}

Node.js v18.9.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[23:05:22] INFO: Installed custom component.
[2024-10-08T23:05:27.624] [INFO] default - Whatsapp Addon started.
[2024-10-08T23:05:32.041] [INFO] default - default client is ready.
/whatsapp.js:240
      throw new WhatsappError(err.output.payload.statusCode);
            ^

WhatsappError: Send message failed. Whatsapp error 428: Connection Closed
    at WhatsappClient.sendPresenceUpdate (/whatsapp.js:240:13) {
  code: 428
}

Node.js v18.9.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[00:08:03] INFO: Installed custom component.
[2024-10-09T00:08:10.111] [INFO] default - Whatsapp Addon started.
[2024-10-09T00:08:11.628] [INFO] default - default client is ready.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[09:47:48] INFO: Installed custom component.
[2024-10-09T09:47:54.772] [INFO] default - Whatsapp Addon started.
[2024-10-09T09:47:56.894] [INFO] default - casa require authentication over QRCode, please see your notifications...
[2024-10-09T09:47:57.573] [INFO] default - default client is ready.
[2024-10-09T09:48:25.517] [INFO] default - casa client is ready.
```

### Additional information

This action requires the clientId field. Enter a valid value for clientId

![wa 09](https://github.com/user-attachments/assets/3c6aa8e6-db6a-4539-9164-b9b5667c225b)
![wa 08](https://github.com/user-attachments/assets/5c052cf2-5875-43f1-aa44-20ec287d1f8c)
![wa 06](https://github.com/user-attachments/assets/dbac5ffb-cb06-4282-84f5-6ee51b09a48b)
![wa 07](https://github.com/user-attachments/assets/86ecb032-870f-4a97-91f1-a22a5f71041f)
![wa 05](https://github.com/user-attachments/assets/285de80f-476d-4fb7-a4dc-4feb5ede636c)
![wa 04](https://github.com/user-attachments/assets/cacdfb5d-f359-405e-90e7-9d0de468cdd3)
![wa 03](https://github.com/user-attachments/assets/2a693032-3bd1-4f57-b8dd-12cb2d0d9a50)
![wa 02](https://github.com/user-attachments/assets/ed34431b-d545-4029-96de-a38f28a56a70)
![wa 01](https://github.com/user-attachments/assets/6d87c4d1-4e50-4612-8e7a-6a2462fa2b90)
![wa 00](https://github.com/user-attachments/assets/05cf2c78-28e7-4397-a0b9-97fed40ae93d)

**Comment by superture** [comment]
Same here but if I use the action in an automation it works
